server:
  port: 8082

spring:
  profiles.active: qa
---


spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 2607
    url: jdbc:mysql://localhost:3306/firstApp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 2607
    url: jdbc:mysql://localhost:3306/firstApp-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---


spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 2607
    url: jdbc:mysql://localhost:3306/firstApp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true